language: python

python:
  - "2.7"

cache: pip

addons:
  apt:
    packages:
    - pdftk

install:
  - pip install -r requirements.txt
  - pip install coverage 
  - pip install coveralls

script:
  - python -m unittest discover -s app/tests
  - coverage run -m unittest discover -s app/tests

after_success:
    coveralls
